export enum WSRequestEvents {
  GET_PROFILE = 'GET_PROFILE',
  PASSWORD_STRENGTH = 'PASSWORD_STRENGTH',
  UPDATE_PROFILE='UPDATE_PROFILE',
  UPDATE_PASSWORD='UPDATE_PASSWORD',
  SEND_EMAIL_VERIFY_TOKEN='SEND_EMAIL_VERIFY_TOKEN',
  SEND_PHONE_VERIFY_TOKEN='SEND_PHONE_VERIFY_TOKEN'
}
