export enum EProfileWebsocketEvents {
  GET_PROFILE = 'GET_PROFILE',
  PASSWORD_STRENGTH = 'PASSWORD_STRENGTH',
  UPDATE_PROFILE='UPDATE_PROFILE',
  UPDATE_PASSWORD='UPDATE_PASSWORD',
  CHECK_EMAIL_BUSY = 'CHECK_EMAIL_BUSY',
  CHECK_PHONE_BUSY = 'CHECK_PHONE_BUSY',
  SEND_EMAIL_VERIFY_TOKEN='SEND_EMAIL_VERIFY_TOKEN',
  SEND_PHONE_VERIFY_TOKEN='SEND_PHONE_VERIFY_TOKEN',
  INFORMATION_MESSAGE='INFORMATION_MESSAGE'
}
