package alexey.grizly.com.users.ws_handlers;

public enum EProfileWSEvents {
    GET_PROFILE,
    PASSWORD_STRENGTH,
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    CHECK_EMAIL_BUSY,
    CHECK_PHONE_BUSY,
    SEND_EMAIL_VERIFY_TOKEN,
    SEND_PHONE_VERIFY_TOKEN,
    INFORMATION_MESSAGE
}
