export enum ERolesWebsocketEvents{
  ALL_ROLES='ALL_ROLES',
  ALL_AUTHORITIES ='ALL_AUTHORITIES',
  AUTHORITIES_BY_ROLE_ID = 'AUTHORITIES_BY_ROLE_ID',
  ROLE_DRAG_DROP = 'ROLE_DRAG_DROP',
  CHECK_ROLE_FOR_DELETE = 'CHECK_ROLE_FOR_DELETE'
}
